[tool.poetry]
name = "polkassist"
version = "0.1.0"
description = ""
authors = ["George Abdala, Felipe G. Martins"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
beautifulsoup4 = "4.12.2"
selenium = "4.9.0"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
